services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=research_user
      - POSTGRES_PASSWORD=secure_password_123
      - POSTGRES_DB=research_db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
