# Generated by Django 5.2.4 on 2025-07-23 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("abstract", models.TextField()),
                ("authors", models.JSONField(help_text="List of author names")),
                ("source", models.CharField(default="arxiv", max_length=50)),
                (
                    "source_id",
                    models.CharField(
                        help_text="The paper's unique ID on its source platform (e.g., arXiv ID)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("pdf_url", models.URLField(max_length=512)),
                (
                    "published_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-published_date"],},
        ),
    ]
